title: "Archer.sh"
description: A simple and intuitive Arch Linux installer. Forked from Anarchy Linux
subdescription: "Join the community on Matrix at #archer:matrix.org"
show_buttons: true
google_analytics:
theme: jekyll-theme-cayman
